spring.application.name=usermanagement

#spring.datasource.url=jdbc:postgresql://docker.for.mac.host.internal:5432/bookmymovie
spring.datasource.url=jdbc:postgresql://localhost:5432/bookmymovie
spring.datasource.username=spring
spring.datasource.password=root
spring.jpa.show-sql=true


# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
#spring.security.user.name=niick
#spring.security.user.password=niick007


server.port=19002