spring.application.name=nexthub-test

# Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

# Cache
spring.cache.type=caffeine

# Caffeine Cache Configuration
spring.cache.cache-names=nodes

# Business Configuration
nexthub.node.max-limit=1000

# Tomcat Request Configuration

# Maximum number of concurrent request processing threads
server.tomcat.threads.max=200

# Minimum spare threads
server.tomcat.threads.min-spare=20

# Maximum connections accepted and processed
server.tomcat.max-connections=1000

# Queue size when all request threads are busy
server.tomcat.accept-count=500