spring.application.name=apigateway
# Admin Port
server.port=9090
spring.threads.virtual.enabled=true
spring.threads.virtual.name-prefix=SPRING-THREAD-POOL-
spring.threads.virtual.max-size=100
spring.threads.worker.core-size=50
spring.threads.worker.queue-capacity=200
# HSQLDB settings
#spring.datasource.url=jdbc:hsqldb:file:./apigatewaydb/gatewaydatabase;shutdown=true
#spring.datasource.driver-class-name=org.hsqldb.jdbcDriver
#spring.datasource.username=sa
#spring.datasource.password=

#PostgreSQL 
spring.datasource.url=jdbc:postgresql://localhost:5432/gateway
spring.datasource.username=gateway_user
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# application.properties
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.pool-name=API-GATEWAY-DB-POOL

spring.jackson.time-zone=Asia/Kolkata
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

#API GATEWAY
apigateway.thread.max=100
apigateway.thread.min=10
apigateway.timeout=60000